jobs:
  unittest_and_bdd_and_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clear cache and update
        run: |
          sudo apt-get clean
          sudo apt-get update

      - name: Install Python and dependencies
        run: |
          sudo apt-get install -y python3-pip gcc
          pip install --upgrade pip
          pip install requests beautifulsoup4 behave

      - name: Run Unit Tests for test.py
        run: |
          python -m unittest test.py  # Corrected command

      - name: Run Unit Tests for test_web_crawler.py
        run: |
          python -m unittest test_web_crawler.py

      - name: TestCrawlerAfterSetup
        run: |
          behave

      - name: Build Docker Image
        run: |
          docker build -t my_web_crawler_image .

      - name: Push Docker Image
        run: |
          docker push gowtham1035/web-search-task:latest
