name: Build Docker Container

on:
  push:
    branches:
      - main
      - master 

jobs:
  unittest_bdd_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clear cache and update
        run: |
          sudo apt-get clean
          sudo apt-get update

      - name: Install Python and dependencies
        run: |
          sudo apt-get install -y python3-pip gcc
          pip install --upgrade pip
          pip install requests beautifulsoup4 behave

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gowtham1035/web-search-task:latest

      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: gowtham1035/web-search-task:latest
