name: Install Dependencies

on:
  push:
    branches:
      - main
      - master 

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache and update
        run: |
          sudo apt-get clean
          sudo apt-get update

      - name: Install Python and dependencies
        run: |
          sudo apt-get install -y python3-pip gcc
          pip install --upgrade pip
          pip install requests beautifulsoup4 behave
